site_name: LHS Practical Guide
site_url: ""
use_directory_urls: false
theme: readthedocs
nav:
    - LHS Practical Guide: index.md
    - LHS Practical Guide (Chinese): index_zh.md
#    - Building ML-enable LHS: ml-lhs/index.html
